### PR TITLE
main.cpp: fix build with gcc-4.9

### PR DESCRIPTION
**Pull request by bkuhls**
Fixes build error:

src/main.cpp:366:45: error: no matching function for call to 'max(double, float)'
         GLfloat r = std::max(sin(delta),0.0f)*0.7f;

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -363,9 +363,9 @@ void CVisualizationMatrix::RenderTo(GLuint shader, GLuint effect_fb)
       {
         double logotimer = std::chrono::duration<double>(std::chrono::high_resolution_clock::now().time_since_epoch()).count();
         float delta = static_cast<float>(logotimer - m_lastAlbumChange)*0.6f;
-        GLfloat r = std::max(sin(delta),0.0f)*0.7f;
-        GLfloat g = std::max(sin(delta - 1.0f),0.0f)*0.7f;
-        GLfloat b = std::max(sin(delta - 2.0f),0.0f)*0.7f;
+        GLfloat r = std::max((float)sin(delta),0.0f)*0.7f;
+        GLfloat g = std::max((float)sin(delta - 1.0f),0.0f)*0.7f;
+        GLfloat b = std::max((float)sin(delta - 2.0f),0.0f)*0.7f;
```
Comment (ksooo) [inline src/main.cpp]: should use c++ style casts

Comment (bkuhls) [reply src/main.cpp]: hopefully done

**Comment by sarbes** [comment]
Builds for me. I whack it in for 1.0.0
